# Kush Framework Configuration
framework:
  name: "Kush Framework"
  version: "3.0.0"
  author: "Kush Team"
  description: "Empire-inspired Penetration Testing Framework"

database:
  path: "./kush.db"
  reset_on_start: false

logging:
  level: "INFO"
  file: "kush.log"
  max_size: "10MB"

listeners:
  default_host: "0.0.0.0"
  default_ports:
    http: 8080
    tcp: 4444

stagers:
  output_dir: "./stagers"
  obfuscation: true

modules:
  enabled_categories:
    - collection
    - persistence
    - privesc
    - recon